### ISSUE TITLE
i2c for Tinkerboard showing up as incorrect instantiations

### ISSUE THREAD

**Issue by kevin-chase-claypool** [rpardini/armbian-release#1]
Rpardini,

Thanks so much for you work on this.  I was able to get Ubuntu 22.04 working via tasksel and its been great.  I tried however to get i2c to function properly for the purpose of having a UPS in case of power surges, and am getting x= i2c-0 i2c-3 and i2c-4 as the instantiations of i2c on the board (using i2cdetect -y x).  Also, I'm getting this: "Error no i2c-bus specified!" when using i2cdetect.

In ASUS documentation, the correct i2c bus enumeration is i2c-6 and i2c-7 .  Is there something that can be done after kernel compilation to make these things work, or are these issues that will need to be rectified in the build process?

Thanks again!
K

**Comment by rpardini** [comment]
See https://twitter.com/SilvioSantoZ/status/1569328762918952960
